### ISSUE TITLE
Interop with unic_locale

### ISSUE THREAD

**Issue by sffc** [google/rust_icu#4]
Maybe you want to use @zbraniecki's Rust Locale class. :smiley:

It looks like all this does is basically call uloc_canonicalize.  IIRC, Zibi's class performs partial but not full canonicalization yet.  Once Zibi's class supports that, maybe you can just remove this wrapper altogether.

**Comment by filmil** [comment]
The value of this wrapper is that it needs no other dependencies beyond ICU.  It matters for https://fuchsia.googlesource.com/, which is then able to use it without taking new dependencies, since the software there already uses ICU.

Which, by the way, is why I'd like to see https://github.com/i18n-concept to define traits that we could implement different ways; and users could then mix and match.

**Comment by filmil** [comment]
I think that `rust_icu` has been established as a self-contained wrapper around icu4c. Since icu4x is already on track to handle pure-rust side of the problem, I tend towards closing this request.
