### ISSUE TITLE
Amend `make publish` to support removing dev-dependencies

### ISSUE THREAD

**Issue by kpozin** [google/rust_icu#96]
crates.io validates all dependencies, including dev-dependencies. If there's an apparent cycle caused by imports in tests, e.g. [ucal] -> [udat] -> [ucal dev], it becomes impossible to publish either crate to crates.io. (See https://github.com/rust-lang/cargo/issues/4242.)

As a workaround, we could have `make publish` something along the lines of:
1. Verify that the git workspace is clean.
1. Back up all Cargo.toml files.
1. Remove or comment out `[dev-dependencies]` from all Cargo.toml files.
1. Run `cargo publish --allow-dirty`, allowing the modified workspace state.
1. Restore the backed up Cargo.toml files.

**Comment by filmil** [comment]
Alternative: is it possible to somehow arrange the crates so that the circular dependency is removed altogether?

**Comment by kpozin** [comment]
We could theoretically move the tests that cause the cycle out into a new crate, but that seems like a risky practice.

**Comment by filmil** [comment]
To short-circuit the search, which crates are forming a cycle?  Perhaps indeed we can move things around so that we don't need to patch things up to publish them.

**Comment by kpozin** [comment]
It's `ucal` and `udat`, because

* `udat` has a method that takes a `&ucal::UCalendar`

https://github.com/google/rust_icu/blob/29ff766701c5fced71b46955f57cc46acba69c8e/rust_icu_udat/src/lib.rs#L147
   
* In `ucal` tests, we're parsing dates (`udat::UDateFormat`)

https://github.com/google/rust_icu/blob/29ff766701c5fced71b46955f57cc46acba69c8e/rust_icu_ucal/src/lib.rs#L422

**Comment by filmil** [comment]
In this particular case, it looks like we could move the test function [`iso_8601_format`](https://github.com/google/rust_icu/blob/29ff766701c5fced71b46955f57cc46acba69c8e/rust_icu_ucal/src/lib.rs#L417) from `ucal` to `udat`, but expose it with `#[cfg(test)]`.  Perhaps we could move other such functions over in a similar vein?

**Comment by filmil** [comment]
I removed my earlier message, since I misunderstood the options we had.

So now I see and understand how this came about.  Given that `rust_icu_udat` is a higher-level crate than `rust_icu_ucal`, it is wrong for tests in `rust_icu_ucal` to require a loop back.  So I kind of side with the crates.io objecting in the end; even though strictly speaking dev deps could be treated separately.

In retrospect, I see that my review recommendation to use date parsing for these few tests have caused this loop back. I wasn't aware that this would be an issue.

Would it be very horrible to lift these tests into `rust_icu_udat`, thus removing the dependency back-link? Yes, we'd be testing UCalendar elsewhere, but it's probably better than fiddling with the release process.

It seems like a better option compared to moving tests to a different crate, since test are still coupled with one of the two crates that are effectively under test.  WDYT?

**Comment by kpozin** [comment]
Could we just avoid the `UDateFormat` dependency and go back to using hard-coded timestamps with comments?

**Comment by filmil** [comment]
> Could we just avoid the `UDateFormat` dependency and go back to using hard-coded timestamps with comments?

Yes, that'd work too.  Feel free to make a pull request to that effect.  I'll remove #101 .

**Comment by filmil** [comment]
One more thing: is there a way to configure cargo to alert us to such dep cycles?
